name: "Hourly README update"

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Revert last commit if it was GitHub Actions
        run: |
          # Revert the last commit if it was GitHub Actions
          if [[ "$(git show -s --format='%ae' HEAD)" == *"github-actions"* ]]; then
            git reset --hard HEAD^;
          fi

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Update core dependencies
        run: |
          pip install -U pip wheel

      - name: Install requirements
        run: |
          pip install -U -r requirements.txt
      
      - name: Generate new README
        run: |
          python generate.py

      - name: Commit and push changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Autogenerated README commit for $(date +%Y-%m-%d_%H-%M)"
          git push --force
